/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TripId = IDL.Nat;
export const AddActivityInput = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Text,
  'tripId' : TripId,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'dayNumber' : IDL.Nat,
  'durationMinutes' : IDL.Nat,
});
export const DestinationId = IDL.Nat;
export const CreateTripInput = IDL.Record({
  'endDate' : IDL.Text,
  'destinationId' : DestinationId,
  'interests' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'budget' : IDL.Nat,
  'startDate' : IDL.Text,
});
export const TripStatus = IDL.Variant({
  'completed' : IDL.Null,
  'planned' : IDL.Null,
  'ongoing' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const ActivityId = IDL.Nat;
export const Activity = IDL.Record({
  'id' : ActivityId,
  'title' : IDL.Text,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'durationMinutes' : IDL.Nat,
});
export const ItineraryDay = IDL.Record({
  'date' : IDL.Text,
  'activities' : IDL.Vec(Activity),
  'dayNumber' : IDL.Nat,
});
export const Trip = IDL.Record({
  'id' : TripId,
  'status' : TripStatus,
  'endDate' : IDL.Text,
  'destinationId' : DestinationId,
  'interests' : IDL.Vec(IDL.Text),
  'userId' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'budget' : IDL.Nat,
  'itinerary' : IDL.Vec(ItineraryDay),
  'startDate' : IDL.Text,
});
export const DestinationFilter = IDL.Record({
  'minRating' : IDL.Opt(IDL.Float64),
  'minBudget' : IDL.Opt(IDL.Nat),
  'tags' : IDL.Vec(IDL.Text),
  'maxBudget' : IDL.Opt(IDL.Nat),
});
export const Destination = IDL.Record({
  'id' : DestinationId,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'activities' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'rating' : IDL.Float64,
  'estimatedDailyBudget' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
});
export const UpdateActivityInput = IDL.Record({
  'title' : IDL.Text,
  'tripId' : TripId,
  'time' : IDL.Text,
  'activityId' : ActivityId,
  'description' : IDL.Text,
  'dayNumber' : IDL.Nat,
  'durationMinutes' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addActivity' : IDL.Func([AddActivityInput], [IDL.Bool], []),
  'createTrip' : IDL.Func([CreateTripInput], [Trip], []),
  'deleteTrip' : IDL.Func([TripId], [IDL.Bool], []),
  'filterDestinations' : IDL.Func(
      [DestinationFilter],
      [IDL.Vec(Destination)],
      ['query'],
    ),
  'getDestination' : IDL.Func(
      [DestinationId],
      [IDL.Opt(Destination)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getOrCreateProfile' : IDL.Func([], [UserProfile], []),
  'getTrip' : IDL.Func([TripId], [IDL.Opt(Trip)], ['query']),
  'listDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
  'listMyTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'removeActivity' : IDL.Func([TripId, IDL.Nat, ActivityId], [IDL.Bool], []),
  'updateActivity' : IDL.Func([UpdateActivityInput], [IDL.Bool], []),
  'updateDisplayName' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateTripStatus' : IDL.Func([TripId, TripStatus], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TripId = IDL.Nat;
  const AddActivityInput = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Text,
    'tripId' : TripId,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'dayNumber' : IDL.Nat,
    'durationMinutes' : IDL.Nat,
  });
  const DestinationId = IDL.Nat;
  const CreateTripInput = IDL.Record({
    'endDate' : IDL.Text,
    'destinationId' : DestinationId,
    'interests' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'budget' : IDL.Nat,
    'startDate' : IDL.Text,
  });
  const TripStatus = IDL.Variant({
    'completed' : IDL.Null,
    'planned' : IDL.Null,
    'ongoing' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const ActivityId = IDL.Nat;
  const Activity = IDL.Record({
    'id' : ActivityId,
    'title' : IDL.Text,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'durationMinutes' : IDL.Nat,
  });
  const ItineraryDay = IDL.Record({
    'date' : IDL.Text,
    'activities' : IDL.Vec(Activity),
    'dayNumber' : IDL.Nat,
  });
  const Trip = IDL.Record({
    'id' : TripId,
    'status' : TripStatus,
    'endDate' : IDL.Text,
    'destinationId' : DestinationId,
    'interests' : IDL.Vec(IDL.Text),
    'userId' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'budget' : IDL.Nat,
    'itinerary' : IDL.Vec(ItineraryDay),
    'startDate' : IDL.Text,
  });
  const DestinationFilter = IDL.Record({
    'minRating' : IDL.Opt(IDL.Float64),
    'minBudget' : IDL.Opt(IDL.Nat),
    'tags' : IDL.Vec(IDL.Text),
    'maxBudget' : IDL.Opt(IDL.Nat),
  });
  const Destination = IDL.Record({
    'id' : DestinationId,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'activities' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'rating' : IDL.Float64,
    'estimatedDailyBudget' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
  });
  const UpdateActivityInput = IDL.Record({
    'title' : IDL.Text,
    'tripId' : TripId,
    'time' : IDL.Text,
    'activityId' : ActivityId,
    'description' : IDL.Text,
    'dayNumber' : IDL.Nat,
    'durationMinutes' : IDL.Nat,
  });
  
  return IDL.Service({
    'addActivity' : IDL.Func([AddActivityInput], [IDL.Bool], []),
    'createTrip' : IDL.Func([CreateTripInput], [Trip], []),
    'deleteTrip' : IDL.Func([TripId], [IDL.Bool], []),
    'filterDestinations' : IDL.Func(
        [DestinationFilter],
        [IDL.Vec(Destination)],
        ['query'],
      ),
    'getDestination' : IDL.Func(
        [DestinationId],
        [IDL.Opt(Destination)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getOrCreateProfile' : IDL.Func([], [UserProfile], []),
    'getTrip' : IDL.Func([TripId], [IDL.Opt(Trip)], ['query']),
    'listDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
    'listMyTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'removeActivity' : IDL.Func([TripId, IDL.Nat, ActivityId], [IDL.Bool], []),
    'updateActivity' : IDL.Func([UpdateActivityInput], [IDL.Bool], []),
    'updateDisplayName' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateTripStatus' : IDL.Func([TripId, TripStatus], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };