/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : ActivityId,
  'title' : string,
  'time' : string,
  'description' : string,
  'durationMinutes' : bigint,
}
export type ActivityId = bigint;
export interface AddActivityInput {
  'title' : string,
  'date' : string,
  'tripId' : TripId,
  'time' : string,
  'description' : string,
  'dayNumber' : bigint,
  'durationMinutes' : bigint,
}
export interface CreateTripInput {
  'endDate' : string,
  'destinationId' : DestinationId,
  'interests' : Array<string>,
  'name' : string,
  'budget' : bigint,
  'startDate' : string,
}
export interface Destination {
  'id' : DestinationId,
  'country' : string,
  'name' : string,
  'tags' : Array<string>,
  'activities' : Array<string>,
  'description' : string,
  'imageUrl' : string,
  'rating' : number,
  'estimatedDailyBudget' : bigint,
}
export interface DestinationFilter {
  'minRating' : [] | [number],
  'minBudget' : [] | [bigint],
  'tags' : Array<string>,
  'maxBudget' : [] | [bigint],
}
export type DestinationId = bigint;
export interface ItineraryDay {
  'date' : string,
  'activities' : Array<Activity>,
  'dayNumber' : bigint,
}
export type Timestamp = bigint;
export interface Trip {
  'id' : TripId,
  'status' : TripStatus,
  'endDate' : string,
  'destinationId' : DestinationId,
  'interests' : Array<string>,
  'userId' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'budget' : bigint,
  'itinerary' : Array<ItineraryDay>,
  'startDate' : string,
}
export type TripId = bigint;
export type TripStatus = { 'completed' : null } |
  { 'planned' : null } |
  { 'ongoing' : null };
export interface UpdateActivityInput {
  'title' : string,
  'tripId' : TripId,
  'time' : string,
  'activityId' : ActivityId,
  'description' : string,
  'dayNumber' : bigint,
  'durationMinutes' : bigint,
}
export type UserId = Principal;
export interface UserProfile {
  'displayName' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
}
export interface _SERVICE {
  'addActivity' : ActorMethod<[AddActivityInput], boolean>,
  'createTrip' : ActorMethod<[CreateTripInput], Trip>,
  'deleteTrip' : ActorMethod<[TripId], boolean>,
  'filterDestinations' : ActorMethod<[DestinationFilter], Array<Destination>>,
  'getDestination' : ActorMethod<[DestinationId], [] | [Destination]>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getOrCreateProfile' : ActorMethod<[], UserProfile>,
  'getTrip' : ActorMethod<[TripId], [] | [Trip]>,
  'listDestinations' : ActorMethod<[], Array<Destination>>,
  'listMyTrips' : ActorMethod<[], Array<Trip>>,
  'removeActivity' : ActorMethod<[TripId, bigint, ActivityId], boolean>,
  'updateActivity' : ActorMethod<[UpdateActivityInput], boolean>,
  'updateDisplayName' : ActorMethod<[string], boolean>,
  'updateTripStatus' : ActorMethod<[TripId, TripStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];