/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UpdateActivityInput {
    title: string;
    tripId: TripId;
    time: string;
    activityId: ActivityId;
    description: string;
    dayNumber: bigint;
    durationMinutes: bigint;
}
export type Timestamp = bigint;
export interface Trip {
    id: TripId;
    status: TripStatus;
    endDate: string;
    destinationId: DestinationId;
    interests: Array<string>;
    userId: UserId;
    name: string;
    createdAt: Timestamp;
    budget: bigint;
    itinerary: Array<ItineraryDay>;
    startDate: string;
}
export interface Destination {
    id: DestinationId;
    country: string;
    name: string;
    tags: Array<string>;
    activities: Array<string>;
    description: string;
    imageUrl: string;
    rating: number;
    estimatedDailyBudget: bigint;
}
export type DestinationId = bigint;
export type UserId = Principal;
export interface ItineraryDay {
    date: string;
    activities: Array<Activity>;
    dayNumber: bigint;
}
export interface DestinationFilter {
    minRating?: number;
    minBudget?: bigint;
    tags: Array<string>;
    maxBudget?: bigint;
}
export interface CreateTripInput {
    endDate: string;
    destinationId: DestinationId;
    interests: Array<string>;
    name: string;
    budget: bigint;
    startDate: string;
}
export type ActivityId = bigint;
export type TripId = bigint;
export interface Activity {
    id: ActivityId;
    title: string;
    time: string;
    description: string;
    durationMinutes: bigint;
}
export interface AddActivityInput {
    title: string;
    date: string;
    tripId: TripId;
    time: string;
    description: string;
    dayNumber: bigint;
    durationMinutes: bigint;
}
export interface UserProfile {
    displayName: string;
    userId: UserId;
    createdAt: Timestamp;
}
export enum TripStatus {
    completed = "completed",
    planned = "planned",
    ongoing = "ongoing"
}
export interface backendInterface {
    addActivity(input: AddActivityInput): Promise<boolean>;
    createTrip(input: CreateTripInput): Promise<Trip>;
    deleteTrip(tripId: TripId): Promise<boolean>;
    filterDestinations(filter: DestinationFilter): Promise<Array<Destination>>;
    getDestination(id: DestinationId): Promise<Destination | null>;
    getMyProfile(): Promise<UserProfile | null>;
    getOrCreateProfile(): Promise<UserProfile>;
    getTrip(tripId: TripId): Promise<Trip | null>;
    listDestinations(): Promise<Array<Destination>>;
    listMyTrips(): Promise<Array<Trip>>;
    removeActivity(tripId: TripId, dayNumber: bigint, activityId: ActivityId): Promise<boolean>;
    updateActivity(input: UpdateActivityInput): Promise<boolean>;
    updateDisplayName(displayName: string): Promise<boolean>;
    updateTripStatus(tripId: TripId, status: TripStatus): Promise<boolean>;
}
import type { Destination as _Destination, DestinationFilter as _DestinationFilter, DestinationId as _DestinationId, ItineraryDay as _ItineraryDay, Timestamp as _Timestamp, Trip as _Trip, TripId as _TripId, TripStatus as _TripStatus, UserId as _UserId, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addActivity(arg0: AddActivityInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addActivity(arg0);
            return result;
        }
    }
    async createTrip(arg0: CreateTripInput): Promise<Trip> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrip(arg0);
                return from_candid_Trip_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrip(arg0);
            return from_candid_Trip_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteTrip(arg0: TripId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrip(arg0);
            return result;
        }
    }
    async filterDestinations(arg0: DestinationFilter): Promise<Array<Destination>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterDestinations(to_candid_DestinationFilter_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterDestinations(to_candid_DestinationFilter_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getDestination(arg0: DestinationId): Promise<Destination | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDestination(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDestination(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrCreateProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrCreateProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrCreateProfile();
            return result;
        }
    }
    async getTrip(arg0: TripId): Promise<Trip | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrip(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrip(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDestinations(): Promise<Array<Destination>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDestinations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDestinations();
            return result;
        }
    }
    async listMyTrips(): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyTrips();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyTrips();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeActivity(arg0: TripId, arg1: bigint, arg2: ActivityId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeActivity(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeActivity(arg0, arg1, arg2);
            return result;
        }
    }
    async updateActivity(arg0: UpdateActivityInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateActivity(arg0);
            return result;
        }
    }
    async updateDisplayName(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDisplayName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDisplayName(arg0);
            return result;
        }
    }
    async updateTripStatus(arg0: TripId, arg1: TripStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTripStatus(arg0, to_candid_TripStatus_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTripStatus(arg0, to_candid_TripStatus_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_TripStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TripStatus): TripStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Trip_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trip): Trip {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Destination]): Destination | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Trip]): Trip | null {
    return value.length === 0 ? null : from_candid_Trip_n1(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TripId;
    status: _TripStatus;
    endDate: string;
    destinationId: _DestinationId;
    interests: Array<string>;
    userId: _UserId;
    name: string;
    createdAt: _Timestamp;
    budget: bigint;
    itinerary: Array<_ItineraryDay>;
    startDate: string;
}): {
    id: TripId;
    status: TripStatus;
    endDate: string;
    destinationId: DestinationId;
    interests: Array<string>;
    userId: UserId;
    name: string;
    createdAt: Timestamp;
    budget: bigint;
    itinerary: Array<ItineraryDay>;
    startDate: string;
} {
    return {
        id: value.id,
        status: from_candid_TripStatus_n3(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        destinationId: value.destinationId,
        interests: value.interests,
        userId: value.userId,
        name: value.name,
        createdAt: value.createdAt,
        budget: value.budget,
        itinerary: value.itinerary,
        startDate: value.startDate
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    planned: null;
} | {
    ongoing: null;
}): TripStatus {
    return "completed" in value ? TripStatus.completed : "planned" in value ? TripStatus.planned : "ongoing" in value ? TripStatus.ongoing : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trip>): Array<Trip> {
    return value.map((x)=>from_candid_Trip_n1(_uploadFile, _downloadFile, x));
}
function to_candid_DestinationFilter_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DestinationFilter): _DestinationFilter {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TripStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TripStatus): _TripStatus {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    minRating?: number;
    minBudget?: bigint;
    tags: Array<string>;
    maxBudget?: bigint;
}): {
    minRating: [] | [number];
    minBudget: [] | [bigint];
    tags: Array<string>;
    maxBudget: [] | [bigint];
} {
    return {
        minRating: value.minRating ? candid_some(value.minRating) : candid_none(),
        minBudget: value.minBudget ? candid_some(value.minBudget) : candid_none(),
        tags: value.tags,
        maxBudget: value.maxBudget ? candid_some(value.maxBudget) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TripStatus): {
    completed: null;
} | {
    planned: null;
} | {
    ongoing: null;
} {
    return value == TripStatus.completed ? {
        completed: null
    } : value == TripStatus.planned ? {
        planned: null
    } : value == TripStatus.ongoing ? {
        ongoing: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
